### ISSUE TITLE
Support for typing.cast call

### ISSUE THREAD

**Issue by rominf** [snok/pep585-upgrade#11]
The code-base I'm modernizing has the following code:
```
project_acl_list = cast(Optional[List[str]], project.acl)
```

Unfortunately, this is not transformed.

I'm willing to fix that, but I don't know yet how...

Could we discuss how to implement the transformation for this code?

**Comment by sondrelg** [comment]
Absolutely!

I'm not an expert either, but you should be able to figure out how it's constructed fairly quickly by loading the code like this

```python
import ast
tree = ast.parse("project_acl_list = cast(Optional[List[str]], project.acl)")
```

and then you can inspect the tree in your local variables if you're using something like pycharm (easiest by far 😄), or if that's no possible, you manually map it by accessing the body, like this-ish

```python
for element in tree.body:
    print(element)
    print(element.__dict__)
```

Let me know if you have any trouble 👏

**Comment by sondrelg** [comment]
This is what it looks like for me 🙂
 
![image](https://user-images.githubusercontent.com/25310870/111499873-b0944e00-8743-11eb-911e-a503ceabdc4e.png)

**Comment by rominf** [comment]
The problem is that `cast` function has too generic a name which could be not from `typing` module, but from somewhere else, so we cannot rely on this. Relying on `Optional` name is also not good, as the code could contain other generic types.

**Comment by sondrelg** [comment]
I should add, you only need the `--py39-plus` flag. Docs: https://github.com/asottile/pyupgrade#pep-585-typing-rewrites

**Comment by rominf** [comment]
If I run `pep585-upgrade` and then `pyupgrade` it doesn't work. Also, `pyupgrade` changes unrelated code. I think I'll resolve issues in manual mode.

**Comment by sondrelg** [comment]
Sounds like a good plan 🙂

I'll close this for now then. Thanks for the report, and you contribution earlier 👏 &nbsp; Good luck upgrading the rest of your project!

**Comment by rominf** [comment]
@sondrelg I think I know the solution, but it requires an additional dependency: astroid, which is used in pylint. The cool thing about astroid is that it allows to do inference. Do you allow me to introduce the dependency which will reduce the number of false positives and false negatives?

**Comment by sondrelg** [comment]
Yes go for it 👍
