### ISSUE TITLE
Create/push a tag for the package

### ISSUE THREAD

**Issue by MRigal** [snok/pep585-upgrade#20]
Hi guys,
Thanks a lot for this great package, it makes the code much more pythonic!
I have one favor: could you create/push a tag for the package? Else I have this annoying warning:

```
[WARNING] The 'rev' field of repo 'https://github.com/snok/pep585-upgrade' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.
```

**Comment by sondrelg** [comment]
Hi @MRigal! Yes that sounds doable haha. I'll create a release as soon as I get a chance 👍

**Comment by sondrelg** [comment]
Would you mind checking whether the issue has been resolved for you now @MRigal? I believe there should be a `v1.0.0` tag, a `v1.0` tag and a `v1` tag available now 🙂

**Comment by MRigal** [comment]
Thanks @sondrelg works like a charm! IMHO, `v1.0.0` classical SemVer would probably be enough for almost everybody, but why not :D
