### ISSUE TITLE
Don't Upgrade Generics

### ISSUE THREAD

**Issue by Kurt-von-Laven** [snok/pep585-upgrade#22]
The `typing` package supports [generics](https://www.python.org/dev/peps/pep-0484/#generics), whereas `collections.abc` does not. Hence, when this tool replaces `typing` types that are used as generics with their equivalent types in `collections.abc`, it breaks the build. I found it helpful to run this tool as a one-off and then manually undo these cases though, so thank you!

**Comment by sondrelg** [comment]
Thanks for reporting this @Kurt-von-Laven; I had no idea the collection types weren't supported for generics! 🙂 

Would you be interested in trying to raise a PR for this? I've not spent a lot of time in the code lately, but think a fix might just require adding an `if` statement or two.

Would you also be able to provide a few concrete examples of when the tool behaves incorrectly? 🙂
