### ISSUE TITLE
pre-commit autoupdate warning

### ISSUE THREAD

**Issue by alkatar21** [snok/pep585-upgrade#28]
Running `pre-commit autoupdate` leads to the following result:
`Updating https://github.com/sondrelg/pep585-upgrade ... updating v1.0.1 -> v1.`

Running `pre-commit autoupdate` again will result in the following warning:
```
[WARNING] The 'rev' field of repo 'https://github.com/sondrelg/pep585-upgrade' appears to be a mutable reference (moving tag / branch).
Mutable references are never updated after first install and are not supported. 
See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details. 
Hint: `pre-commit autoupdate` often fixes this.
```

It would be cool if `pre-commit autoupdate` would work on this hook as expected. I suspect that the problem is that all 3 tags point to the same commit.

**Comment by sondrelg** [comment]
I'm a bit torn on what to do, since removing the v1/v1.0 tags might break people's environments if they've already specified those explicitly right. It also seems weird to me that pre-commit upgrades to a mutable reference yet complains about it.

Then again, this is a pre-commit hook primarily, and it might make sense to just get rid of the unfit tags. 

What do you think? 

@JonasKs, do you have a take on this?

**Comment by alkatar21** [comment]
I don't know if the problem will solve itself with the next release, if there is only 1.0.2 or 1.1.0 on the latest commit, depending on what it will be?

**Comment by sondrelg** [comment]
I think v1.2.0 would still be upgraded to v1, so a v2 release would be necessary to resolve the issue. Doubt pre-commit autoupdate will upgrade to v2 for you, so not sure that's a good solution either (but happy to be proven wrong about both points).

**Comment by alkatar21** [comment]
I think a v2 will not solve the problem, at most v2.0.0 maybe. But I don't know that for sure. If it doesn't, only deleting would help, though I also see the problem that comes with that.
Whereby there is then either no update possibility or possibly some not working configs as alternatives. I would prefer the update option in the long run.

**Comment by sondrelg** [comment]
I'm officially deprecating this project, as `pyupgrade` now fills the gap this once did. The package can still be used, but I'm not intending to spend any more time maintaining it, so closing this for now 🙂
