### ISSUE TITLE
don't add another import line from same package

### ISSUE THREAD

**Issue by kretes** [snok/pep585-upgrade#29]
For an input file like this:
```
from collections.abc import Callable

from typing import Collection

def a(a: Callable, b: Collection):
    pass
```

when applying pep585 hook I get:
```
from collections.abc import Collection
from collections.abc import Callable

def a(a: Callable, b: Collection):
    pass
```

while I expect:
```
from collections.abc import Callable, Collection

def a(a: Callable, b: Collection):
    pass
```

It could be argued this is the job of e.g. `isort`, however - `pep585-upgrade` already tries to be nice in terms of imports - e.g. in a larger import set - this new import line gets added nearby other import from same package and not at the end (which would be simplest I guess)

**Comment by sondrelg** [comment]
PRs are welcome, but I would indeed argue that this is out of scope for the package. Better to pair it with `isort` and call it a day in my opinion.

Pyupgrade also supports upgrading some of these type hints now (didn't when I wrote this), so I'd consider this package more useful as sort of a codemod for entire projects, to do one-time upgrades.
