### ISSUE TITLE
Import of ClassVar is replaced by ClassVarVar

### ISSUE THREAD

**Issue by NeilGirdhar** [snok/pep585-upgrade#3]
```python
from dataclasses import dataclass
from typing import ClassVar

@dataclass
class C:
    mu: ClassVar[float] = 2.0
```

**Comment by sondrelg** [comment]
Thanks for submitting the issue. I'm not able to reproduce the error with the example provided here. 

Running the hook on 

```python
from dataclasses import dataclass
from typing import ClassVar, List


@dataclass
class C:
    mu: ClassVar[float] = 2.0
    x: List[str]
```

produces 

```python
from dataclasses import dataclass
from typing import ClassVar


@dataclass
class C:
    mu: ClassVar[float] = 2.0
    x: list[str]
```

but running it on your example doesn't actually trigger any changes. The `ClassVar` type isn't a part of pep585 either, so it's not something we look for. Is it possible that another hook is the culprit, or the example needs to be adjusted? 

If you want to clone the repo and create a reproducible example you can run the hook like this `python -m upgrade_type_hints ../tests/example_files/classvar.py`.

Hope that helps you :)

**Comment by sondrelg** [comment]
What Python version were you running btw? If you're running Pyton < 3.9, the changes in https://github.com/snok/pep585-upgrade/pull/4 might help.

**Comment by NeilGirdhar** [comment]
I'm running on 3.9.  Sorry, I didn't want to spend time making a MWE.  I also saw other problems like `from __future__ import annotations` being added even when I already have one, and some things not being converted to `collections.abc` from typing like they should be.  Anyway, feel free to close this.

It's still a useful tool.  I'll use it again next time I need to do this.

**Comment by sondrelg** [comment]
> from __future__ import annotations being added even when I already have one

I'll make sure to correct this 👍  Thanks for the feedback

**Comment by NeilGirdhar** [comment]
You're very welcome, thanks for the great tool.  It definitely saved me a good chunk of laborious work.
